country = Spree::Country.find_by(name: 'Chile', iso_name: 'CHILE', iso: 'CL', iso3: 'CHL', numcode: 152)
country.update(states_required: false)
country.update(zipcode_required: false)

# Chilean states
xv   = Spree::State.find_or_create_by(name: 'Arica y Parinacota', abbr: 'AP', country:)
i    = Spree::State.find_or_create_by(name: 'Tarapacá', abbr: 'TA', country:)
ii   = Spree::State.find_or_create_by(name: 'Antofagasta', abbr: 'AN', country:)
iii  = Spree::State.find_or_create_by(name: 'Atacama', abbr: 'AT', country:)
iv   = Spree::State.find_or_create_by(name: 'Coquimbo', abbr: 'CO', country:)
v    = Spree::State.find_or_create_by(name: 'Valparaíso', abbr: 'VS', country:)
vi   = Spree::State.find_or_create_by(name: 'Libertador General Bernardo O\'Higgins', abbr: 'LI', country:)
vii  = Spree::State.find_or_create_by(name: 'Maule', abbr: 'ML', country:)
viii = Spree::State.find_or_create_by(name: 'Bío-Bío', abbr: 'BI', country:)
ix   = Spree::State.find_or_create_by(name: 'Araucanía', abbr: 'AR', country:)
x    = Spree::State.find_or_create_by(name: 'Los Lagos', abbr: 'LL', country:)
xi   = Spree::State.find_or_create_by(name: 'Aisén del General Carlos Ibáñez del Campo', abbr: 'AI', country:)
xii  = Spree::State.find_or_create_by(name: 'Magallanes y Antártica Chilena', abbr: 'MA', country:)
rm   = Spree::State.find_or_create_by(name: 'Región Metropolitana de Santiago', abbr: 'RM', country:)
xiv  = Spree::State.find_or_create_by(name: 'Los Ríos', abbr: 'LR', country:)

# Chilean counties
Spree::County.find_or_create_by(name: 'Arica',                code: '15101', state: xv)
Spree::County.find_or_create_by(name: 'Camarones',            code: '15102', state: xv)
Spree::County.find_or_create_by(name: 'Putre',                code: '15201', state: xv)
Spree::County.find_or_create_by(name: 'General Lagos',        code: '15202', state: xv)
Spree::County.find_or_create_by(name: 'Iquique',              code: '01101', state: i)
Spree::County.find_or_create_by(name: 'Alto Hospicio',        code: '01107', state: i)
Spree::County.find_or_create_by(name: 'Pozo Almonte',         code: '01401', state: i)
Spree::County.find_or_create_by(name: 'Camiña',               code: '01402', state: i)
Spree::County.find_or_create_by(name: 'Colchane',             code: '01403', state: i)
Spree::County.find_or_create_by(name: 'Huara',                code: '01404', state: i)
Spree::County.find_or_create_by(name: 'Pica',                 code: '01405', state: i)
Spree::County.find_or_create_by(name: 'Antofagasta',          code: '02101', state: ii)
Spree::County.find_or_create_by(name: 'Mejillones',           code: '02102', state: ii)
Spree::County.find_or_create_by(name: 'Sierra Gorda',         code: '02103', state: ii)
Spree::County.find_or_create_by(name: 'Taltal',               code: '02104', state: ii)
Spree::County.find_or_create_by(name: 'Calama',               code: '02201', state: ii)
Spree::County.find_or_create_by(name: 'Ollagüe',              code: '02202', state: ii)
Spree::County.find_or_create_by(name: 'San Pedro de Atacama', code: '02203', state: ii)
Spree::County.find_or_create_by(name: 'Tocopilla',            code: '02301', state: ii)
Spree::County.find_or_create_by(name: 'María Elena',          code: '02302', state: ii)
Spree::County.find_or_create_by(name: 'Copiapó',              code: '03101', state: iii)
Spree::County.find_or_create_by(name: 'Caldera',              code: '03102', state: iii)
Spree::County.find_or_create_by(name: 'Tierra Amarilla',      code: '03103', state: iii)
Spree::County.find_or_create_by(name: 'Chañaral',             code: '03201', state: iii)
Spree::County.find_or_create_by(name: 'Diego de Almagro',     code: '03202', state: iii)
Spree::County.find_or_create_by(name: 'Vallenar',             code: '03301', state: iii)
Spree::County.find_or_create_by(name: 'Alto del Carmen',      code: '03302', state: iii)
Spree::County.find_or_create_by(name: 'Freirina',             code: '03303', state: iii)
Spree::County.find_or_create_by(name: 'Huasco',               code: '03304', state: iii)
Spree::County.find_or_create_by(name: 'La Serena',            code: '04101', state: iv)
Spree::County.find_or_create_by(name: 'Coquimbo',             code: '04102', state: iv)
Spree::County.find_or_create_by(name: 'Andacollo',            code: '04103', state: iv)
Spree::County.find_or_create_by(name: 'La Higuera',           code: '04104', state: iv)
Spree::County.find_or_create_by(name: 'Paiguano',             code: '04105', state: iv)
Spree::County.find_or_create_by(name: 'Vicuña',               code: '04106', state: iv)
Spree::County.find_or_create_by(name: 'Illapel',              code: '04201', state: iv)
Spree::County.find_or_create_by(name: 'Canela',               code: '04202', state: iv)
Spree::County.find_or_create_by(name: 'Los Vilos',            code: '04203', state: iv)
Spree::County.find_or_create_by(name: 'Salamanca',            code: '04204', state: iv)
Spree::County.find_or_create_by(name: 'Ovalle',               code: '04301', state: iv)
Spree::County.find_or_create_by(name: 'Combarbalá',           code: '04302', state: iv)
Spree::County.find_or_create_by(name: 'Monte Patria',         code: '04303', state: iv)
Spree::County.find_or_create_by(name: 'Punitaqui',            code: '04304', state: iv)
Spree::County.find_or_create_by(name: 'Río Hurtado',          code: '04305', state: iv)
Spree::County.find_or_create_by(name: 'Valparaíso',           code: '05101', state: v)
Spree::County.find_or_create_by(name: 'Casablanca',           code: '05102', state: v)
Spree::County.find_or_create_by(name: 'Concón',               code: '05103', state: v)
Spree::County.find_or_create_by(name: 'Juan Fernández',       code: '05104', state: v)
Spree::County.find_or_create_by(name: 'Puchuncaví',           code: '05105', state: v)
Spree::County.find_or_create_by(name: 'Quintero',             code: '05107', state: v)
Spree::County.find_or_create_by(name: 'Viña del Mar',         code: '05109', state: v)
Spree::County.find_or_create_by(name: 'Isla de Pascua',       code: '05201', state: v)
Spree::County.find_or_create_by(name: 'Los Andes',            code: '05301', state: v)
Spree::County.find_or_create_by(name: 'Calle Larga',          code: '05302', state: v)
Spree::County.find_or_create_by(name: 'Rinconada',            code: '05303', state: v)
Spree::County.find_or_create_by(name: 'San Esteban',          code: '05304', state: v)
Spree::County.find_or_create_by(name: 'La Ligua',             code: '05401', state: v)
Spree::County.find_or_create_by(name: 'Cabildo',              code: '05402', state: v)
Spree::County.find_or_create_by(name: 'Papudo',               code: '05403', state: v)
Spree::County.find_or_create_by(name: 'Petorca',              code: '05404', state: v)
Spree::County.find_or_create_by(name: 'Zapallar',             code: '05405', state: v)
Spree::County.find_or_create_by(name: 'Quillota',             code: '05501', state: v)
Spree::County.find_or_create_by(name: 'Calera',               code: '05502', state: v)
Spree::County.find_or_create_by(name: 'Hijuelas',             code: '05503', state: v)
Spree::County.find_or_create_by(name: 'La Cruz',              code: '05504', state: v)
Spree::County.find_or_create_by(name: 'Nogales',              code: '05506', state: v)
Spree::County.find_or_create_by(name: 'San Antonio',          code: '05601', state: v)
Spree::County.find_or_create_by(name: 'Algarrobo',            code: '05602', state: v)
Spree::County.find_or_create_by(name: 'Cartagena',            code: '05603', state: v)
Spree::County.find_or_create_by(name: 'El Quisco',            code: '05604', state: v)
Spree::County.find_or_create_by(name: 'El Tabo',              code: '05605', state: v)
Spree::County.find_or_create_by(name: 'Santo Domingo',        code: '05606', state: v)
Spree::County.find_or_create_by(name: 'San Felipe',           code: '05701', state: v)
Spree::County.find_or_create_by(name: 'Catemu',               code: '05702', state: v)
Spree::County.find_or_create_by(name: 'Llaillay',             code: '05703', state: v)
Spree::County.find_or_create_by(name: 'Panquehue',            code: '05704', state: v)
Spree::County.find_or_create_by(name: 'Putaendo',             code: '05705', state: v)
Spree::County.find_or_create_by(name: 'Santa María',          code: '05706', state: v)
Spree::County.find_or_create_by(name: 'Limache',              code: '05802', state: v)
Spree::County.find_or_create_by(name: 'Quilpué',              code: '05801', state: v)
Spree::County.find_or_create_by(name: 'Villa Alemana',        code: '05804', state: v)
Spree::County.find_or_create_by(name: 'Olmué',                code: '05803', state: v)
Spree::County.find_or_create_by(name: 'Rancagua',             code: '06101', state: vi)
Spree::County.find_or_create_by(name: 'Codegua',              code: '06102', state: vi)
Spree::County.find_or_create_by(name: 'Coinco',               code: '06103', state: vi)
Spree::County.find_or_create_by(name: 'Coltauco',             code: '06104', state: vi)
Spree::County.find_or_create_by(name: 'Doñihue',              code: '06105', state: vi)
Spree::County.find_or_create_by(name: 'Graneros',             code: '06106', state: vi)
Spree::County.find_or_create_by(name: 'Las Cabras',           code: '06107', state: vi)
Spree::County.find_or_create_by(name: 'Machalí',              code: '06108', state: vi)
Spree::County.find_or_create_by(name: 'Malloa',               code: '06109', state: vi)
Spree::County.find_or_create_by(name: 'Mostazal',             code: '06110', state: vi)
Spree::County.find_or_create_by(name: 'Olivar',               code: '06111', state: vi)
Spree::County.find_or_create_by(name: 'Peumo',                code: '06112', state: vi)
Spree::County.find_or_create_by(name: 'Pichidegua',           code: '06113', state: vi)
Spree::County.find_or_create_by(name: 'Quinta de Tilcoco',    code: '06114', state: vi)
Spree::County.find_or_create_by(name: 'Rengo',                code: '06115', state: vi)
Spree::County.find_or_create_by(name: 'Requínoa',             code: '06116', state: vi)
Spree::County.find_or_create_by(name: 'San Vicente',          code: '06117', state: vi)
Spree::County.find_or_create_by(name: 'Pichilemu',            code: '06201', state: vi)
Spree::County.find_or_create_by(name: 'La Estrella',          code: '06202', state: vi)
Spree::County.find_or_create_by(name: 'Litueche',             code: '06203', state: vi)
Spree::County.find_or_create_by(name: 'Marchihue',            code: '06204', state: vi)
Spree::County.find_or_create_by(name: 'Navidad',              code: '06205', state: vi)
Spree::County.find_or_create_by(name: 'Paredones',            code: '06206', state: vi)
Spree::County.find_or_create_by(name: 'San Fernando',         code: '06301', state: vi)
Spree::County.find_or_create_by(name: 'Chépica',              code: '06302', state: vi)
Spree::County.find_or_create_by(name: 'Chimbarongo',          code: '06303', state: vi)
Spree::County.find_or_create_by(name: 'Lolol',                code: '06304', state: vi)
Spree::County.find_or_create_by(name: 'Nancagua',             code: '06305', state: vi)
Spree::County.find_or_create_by(name: 'Palmilla',             code: '06306', state: vi)
Spree::County.find_or_create_by(name: 'Peralillo',            code: '06307', state: vi)
Spree::County.find_or_create_by(name: 'Placilla',             code: '06308', state: vi)
Spree::County.find_or_create_by(name: 'Pumanque',             code: '06309', state: vi)
Spree::County.find_or_create_by(name: 'Santa Cruz',           code: '06310', state: vi)
Spree::County.find_or_create_by(name: 'Talca',                code: '07101', state: vii)
Spree::County.find_or_create_by(name: 'Constitución',         code: '07102', state: vii)
Spree::County.find_or_create_by(name: 'Curepto',              code: '07103', state: vii)
Spree::County.find_or_create_by(name: 'Empedrado',            code: '07104', state: vii)
Spree::County.find_or_create_by(name: 'Maule',                code: '07105', state: vii)
Spree::County.find_or_create_by(name: 'Pelarco',              code: '07106', state: vii)
Spree::County.find_or_create_by(name: 'Pencahue',             code: '07107', state: vii)
Spree::County.find_or_create_by(name: 'Río Claro',            code: '07108', state: vii)
Spree::County.find_or_create_by(name: 'San Clemente',         code: '07109', state: vii)
Spree::County.find_or_create_by(name: 'San Rafael',           code: '07110', state: vii)
Spree::County.find_or_create_by(name: 'Cauquenes',            code: '07201', state: vii)
Spree::County.find_or_create_by(name: 'Chanco',               code: '07202', state: vii)
Spree::County.find_or_create_by(name: 'Pelluhue',             code: '07203', state: vii)
Spree::County.find_or_create_by(name: 'Curicó',               code: '07301', state: vii)
Spree::County.find_or_create_by(name: 'Hualañé',              code: '07302', state: vii)
Spree::County.find_or_create_by(name: 'Licantén',             code: '07303', state: vii)
Spree::County.find_or_create_by(name: 'Molina',               code: '07304', state: vii)
Spree::County.find_or_create_by(name: 'Rauco',                code: '07305', state: vii)
Spree::County.find_or_create_by(name: 'Romeral',              code: '07306', state: vii)
Spree::County.find_or_create_by(name: 'Sagrada Familia',      code: '07307', state: vii)
Spree::County.find_or_create_by(name: 'Teno',                 code: '07308', state: vii)
Spree::County.find_or_create_by(name: 'Vichuquén',            code: '07309', state: vii)
Spree::County.find_or_create_by(name: 'Linares',              code: '07401', state: vii)
Spree::County.find_or_create_by(name: 'Colbún',               code: '07402', state: vii)
Spree::County.find_or_create_by(name: 'Longaví',              code: '07403', state: vii)
Spree::County.find_or_create_by(name: 'Parral',               code: '07404', state: vii)
Spree::County.find_or_create_by(name: 'Retiro',               code: '07405', state: vii)
Spree::County.find_or_create_by(name: 'San Javier',           code: '07406', state: vii)
Spree::County.find_or_create_by(name: 'Villa Alegre',         code: '07407', state: vii)
Spree::County.find_or_create_by(name: 'Yerbas Buenas',        code: '07408', state: vii)
Spree::County.find_or_create_by(name: 'Concepción',           code: '08101', state: viii)
Spree::County.find_or_create_by(name: 'Coronel',              code: '08102', state: viii)
Spree::County.find_or_create_by(name: 'Chiguayante',          code: '08103', state: viii)
Spree::County.find_or_create_by(name: 'Florida',              code: '08104', state: viii)
Spree::County.find_or_create_by(name: 'Hualqui',              code: '08105', state: viii)
Spree::County.find_or_create_by(name: 'Lota',                 code: '08106', state: viii)
Spree::County.find_or_create_by(name: 'Penco',                code: '08107', state: viii)
Spree::County.find_or_create_by(name: 'San Pedro de la Paz',  code: '08108', state: viii)
Spree::County.find_or_create_by(name: 'Santa Juana',          code: '08109', state: viii)
Spree::County.find_or_create_by(name: 'Talcahuano',           code: '08110', state: viii)
Spree::County.find_or_create_by(name: 'Tomé',                 code: '08111', state: viii)
Spree::County.find_or_create_by(name: 'Hualpén',              code: '08112', state: viii)
Spree::County.find_or_create_by(name: 'Lebu',                 code: '08201', state: viii)
Spree::County.find_or_create_by(name: 'Arauco',               code: '08202', state: viii)
Spree::County.find_or_create_by(name: 'Cañete',               code: '08203', state: viii)
Spree::County.find_or_create_by(name: 'Contulmo',             code: '08204', state: viii)
Spree::County.find_or_create_by(name: 'Curanilahue',          code: '08205', state: viii)
Spree::County.find_or_create_by(name: 'Los Alamos',           code: '08206', state: viii)
Spree::County.find_or_create_by(name: 'Tirúa',                code: '08207', state: viii)
Spree::County.find_or_create_by(name: 'Los Angeles',          code: '08301', state: viii)
Spree::County.find_or_create_by(name: 'Antuco',               code: '08302', state: viii)
Spree::County.find_or_create_by(name: 'Cabrero',              code: '08303', state: viii)
Spree::County.find_or_create_by(name: 'Laja',                 code: '08304', state: viii)
Spree::County.find_or_create_by(name: 'Mulchén',              code: '08305', state: viii)
Spree::County.find_or_create_by(name: 'Nacimiento',           code: '08306', state: viii)
Spree::County.find_or_create_by(name: 'Negrete',              code: '08307', state: viii)
Spree::County.find_or_create_by(name: 'Quilaco',              code: '08308', state: viii)
Spree::County.find_or_create_by(name: 'Quilleco',             code: '08309', state: viii)
Spree::County.find_or_create_by(name: 'San Rosendo',          code: '08310', state: viii)
Spree::County.find_or_create_by(name: 'Santa Bárbara',        code: '08311', state: viii)
Spree::County.find_or_create_by(name: 'Tucapel',              code: '08312', state: viii)
Spree::County.find_or_create_by(name: 'Yumbel',               code: '08313', state: viii)
Spree::County.find_or_create_by(name: 'Alto Biobío',          code: '08314', state: viii)
Spree::County.find_or_create_by(name: 'Chillán',              code: '08401', state: viii)
Spree::County.find_or_create_by(name: 'Bulnes',               code: '08402', state: viii)
Spree::County.find_or_create_by(name: 'Cobquecura',           code: '08403', state: viii)
Spree::County.find_or_create_by(name: 'Coelemu',              code: '08404', state: viii)
Spree::County.find_or_create_by(name: 'Coihueco',             code: '08405', state: viii)
Spree::County.find_or_create_by(name: 'Chillán Viejo',        code: '08406', state: viii)
Spree::County.find_or_create_by(name: 'El Carmen',            code: '08407', state: viii)
Spree::County.find_or_create_by(name: 'Ninhue',               code: '08408', state: viii)
Spree::County.find_or_create_by(name: 'Ñiquén',               code: '08409', state: viii)
Spree::County.find_or_create_by(name: 'Pemuco',               code: '08410', state: viii)
Spree::County.find_or_create_by(name: 'Pinto',                code: '08411', state: viii)
Spree::County.find_or_create_by(name: 'Portezuelo',           code: '08412', state: viii)
Spree::County.find_or_create_by(name: 'Quillón',              code: '08413', state: viii)
Spree::County.find_or_create_by(name: 'Quirihue',             code: '08414', state: viii)
Spree::County.find_or_create_by(name: 'Ránquil',              code: '08415', state: viii)
Spree::County.find_or_create_by(name: 'San Carlos',           code: '08416', state: viii)
Spree::County.find_or_create_by(name: 'San Fabián',           code: '08417', state: viii)
Spree::County.find_or_create_by(name: 'San Ignacio',          code: '08418', state: viii)
Spree::County.find_or_create_by(name: 'San Nicolás',          code: '08419', state: viii)
Spree::County.find_or_create_by(name: 'Treguaco',             code: '08420', state: viii)
Spree::County.find_or_create_by(name: 'Yungay',               code: '08421', state: viii)
Spree::County.find_or_create_by(name: 'Temuco',               code: '09101', state: ix)
Spree::County.find_or_create_by(name: 'Carahue',              code: '09102', state: ix)
Spree::County.find_or_create_by(name: 'Cunco',                code: '09103', state: ix)
Spree::County.find_or_create_by(name: 'Curarrehue',           code: '09104', state: ix)
Spree::County.find_or_create_by(name: 'Freire',               code: '09105', state: ix)
Spree::County.find_or_create_by(name: 'Galvarino',            code: '09106', state: ix)
Spree::County.find_or_create_by(name: 'Gorbea',               code: '09107', state: ix)
Spree::County.find_or_create_by(name: 'Lautaro',              code: '09108', state: ix)
Spree::County.find_or_create_by(name: 'Loncoche',             code: '09109', state: ix)
Spree::County.find_or_create_by(name: 'Melipeuco',            code: '09110', state: ix)
Spree::County.find_or_create_by(name: 'Nueva Imperial',       code: '09111', state: ix)
Spree::County.find_or_create_by(name: 'Padre Las Casas',      code: '09112', state: ix)
Spree::County.find_or_create_by(name: 'Perquenco',            code: '09113', state: ix)
Spree::County.find_or_create_by(name: 'Pitrufquén',           code: '09114', state: ix)
Spree::County.find_or_create_by(name: 'Pucón',                code: '09115', state: ix)
Spree::County.find_or_create_by(name: 'Saavedra',             code: '09116', state: ix)
Spree::County.find_or_create_by(name: 'Teodoro Schmidt',      code: '09117', state: ix)
Spree::County.find_or_create_by(name: 'Toltén',               code: '09118', state: ix)
Spree::County.find_or_create_by(name: 'Vilcún',               code: '09119', state: ix)
Spree::County.find_or_create_by(name: 'Villarrica',           code: '09120', state: ix)
Spree::County.find_or_create_by(name: 'Cholchol',             code: '09121', state: ix)
Spree::County.find_or_create_by(name: 'Angol',                code: '09201', state: ix)
Spree::County.find_or_create_by(name: 'Collipulli',           code: '09202', state: ix)
Spree::County.find_or_create_by(name: 'Curacautín',           code: '09203', state: ix)
Spree::County.find_or_create_by(name: 'Ercilla',              code: '09204', state: ix)
Spree::County.find_or_create_by(name: 'Lonquimay',            code: '09205', state: ix)
Spree::County.find_or_create_by(name: 'Los Sauces',           code: '09206', state: ix)
Spree::County.find_or_create_by(name: 'Lumaco',               code: '09207', state: ix)
Spree::County.find_or_create_by(name: 'Purén',                code: '09208', state: ix)
Spree::County.find_or_create_by(name: 'Renaico',              code: '09209', state: ix)
Spree::County.find_or_create_by(name: 'Traiguén',             code: '09210', state: ix)
Spree::County.find_or_create_by(name: 'Victoria',             code: '09211', state: ix)
Spree::County.find_or_create_by(name: 'Valdivia',             code: '14101', state: xiv)
Spree::County.find_or_create_by(name: 'Corral',               code: '14102', state: xiv)
Spree::County.find_or_create_by(name: 'Lanco',                code: '14103', state: xiv)
Spree::County.find_or_create_by(name: 'Los Lagos',            code: '14104', state: xiv)
Spree::County.find_or_create_by(name: 'Máfil',                code: '14105', state: xiv)
Spree::County.find_or_create_by(name: 'Mariquina',            code: '14106', state: xiv)
Spree::County.find_or_create_by(name: 'Paillaco',             code: '14107', state: xiv)
Spree::County.find_or_create_by(name: 'Panguipulli',          code: '14108', state: xiv)
Spree::County.find_or_create_by(name: 'La Unión',             code: '14201', state: xiv)
Spree::County.find_or_create_by(name: 'Futrono',              code: '14202', state: xiv)
Spree::County.find_or_create_by(name: 'Lago Ranco',           code: '14203', state: xiv)
Spree::County.find_or_create_by(name: 'Río Bueno',            code: '14204', state: xiv)
Spree::County.find_or_create_by(name: 'Puerto Montt',         code: '10101', state: x)
Spree::County.find_or_create_by(name: 'Calbuco',              code: '10102', state: x)
Spree::County.find_or_create_by(name: 'Cochamó',              code: '10103', state: x)
Spree::County.find_or_create_by(name: 'Fresia',               code: '10104', state: x)
Spree::County.find_or_create_by(name: 'Frutillar',            code: '10105', state: x)
Spree::County.find_or_create_by(name: 'Los Muermos',          code: '10106', state: x)
Spree::County.find_or_create_by(name: 'Llanquihue',           code: '10107', state: x)
Spree::County.find_or_create_by(name: 'Maullín',              code: '10108', state: x)
Spree::County.find_or_create_by(name: 'Puerto Varas',         code: '10109', state: x)
Spree::County.find_or_create_by(name: 'Castro',               code: '10201', state: x)
Spree::County.find_or_create_by(name: 'Ancud',                code: '10202', state: x)
Spree::County.find_or_create_by(name: 'Chonchi',              code: '10203', state: x)
Spree::County.find_or_create_by(name: 'Curaco de Vélez',      code: '10204', state: x)
Spree::County.find_or_create_by(name: 'Dalcahue',             code: '10205', state: x)
Spree::County.find_or_create_by(name: 'Puqueldón',            code: '10206', state: x)
Spree::County.find_or_create_by(name: 'Queilén',              code: '10207', state: x)
Spree::County.find_or_create_by(name: 'Quellón',              code: '10208', state: x)
Spree::County.find_or_create_by(name: 'Quemchi',              code: '10209', state: x)
Spree::County.find_or_create_by(name: 'Quinchao',             code: '10210', state: x)
Spree::County.find_or_create_by(name: 'Osorno',               code: '10301', state: x)
Spree::County.find_or_create_by(name: 'Puerto Octay',         code: '10302', state: x)
Spree::County.find_or_create_by(name: 'Purranque',            code: '10303', state: x)
Spree::County.find_or_create_by(name: 'Puyehue',              code: '10304', state: x)
Spree::County.find_or_create_by(name: 'Río Negro',            code: '10305', state: x)
Spree::County.find_or_create_by(name: 'San Juan de la Costa', code: '10306', state: x)
Spree::County.find_or_create_by(name: 'San Pablo',            code: '10307', state: x)
Spree::County.find_or_create_by(name: 'Chaitén',              code: '10401', state: x)
Spree::County.find_or_create_by(name: 'Futaleufú',            code: '10402', state: x)
Spree::County.find_or_create_by(name: 'Hualaihué',            code: '10403', state: x)
Spree::County.find_or_create_by(name: 'Palena',               code: '10404', state: x)
Spree::County.find_or_create_by(name: 'Coihaique',            code: '11101', state: xi)
Spree::County.find_or_create_by(name: 'Lago Verde',           code: '11102', state: xi)
Spree::County.find_or_create_by(name: 'Aisén',                code: '11201', state: xi)
Spree::County.find_or_create_by(name: 'Cisnes',               code: '11202', state: xi)
Spree::County.find_or_create_by(name: 'Guaitecas',            code: '11203', state: xi)
Spree::County.find_or_create_by(name: 'Cochrane',             code: '11301', state: xi)
Spree::County.find_or_create_by(name: 'O\'Higgins',           code: '11302', state: xi)
Spree::County.find_or_create_by(name: 'Tortel',               code: '11303', state: xi)
Spree::County.find_or_create_by(name: 'Chile Chico',          code: '11401', state: xi)
Spree::County.find_or_create_by(name: 'Río Ibáñez',           code: '11402', state: xi)
Spree::County.find_or_create_by(name: 'Punta Arenas',         code: '12101', state: xii)
Spree::County.find_or_create_by(name: 'Laguna Blanca',        code: '12102', state: xii)
Spree::County.find_or_create_by(name: 'Río Verde',            code: '12103', state: xii)
Spree::County.find_or_create_by(name: 'San Gregorio',         code: '12104', state: xii)
Spree::County.find_or_create_by(name: 'Cabo de Hornos',       code: '12201', state: xii)
Spree::County.find_or_create_by(name: 'Antártica',            code: '12202', state: xii)
Spree::County.find_or_create_by(name: 'Porvenir',             code: '12301', state: xii)
Spree::County.find_or_create_by(name: 'Primavera',            code: '12302', state: xii)
Spree::County.find_or_create_by(name: 'Timaukel',             code: '12303', state: xii)
Spree::County.find_or_create_by(name: 'Natales',              code: '12401', state: xii)
Spree::County.find_or_create_by(name: 'Torres del Paine',     code: '12402', state: xii)
Spree::County.find_or_create_by(name: 'Colina',               code: '13301', state: rm)
Spree::County.find_or_create_by(name: 'Lampa',                code: '13302', state: rm)
Spree::County.find_or_create_by(name: 'Tiltil',               code: '13303', state: rm)
Spree::County.find_or_create_by(name: 'Pirque',               code: '13202', state: rm)
Spree::County.find_or_create_by(name: 'Puente Alto',          code: '13201', state: rm)
Spree::County.find_or_create_by(name: 'San José de Maipo',    code: '13203', state: rm)
Spree::County.find_or_create_by(name: 'Buin',                 code: '13402', state: rm)
Spree::County.find_or_create_by(name: 'Calera de Tango',      code: '13403', state: rm)
Spree::County.find_or_create_by(name: 'Paine',                code: '13404', state: rm)
Spree::County.find_or_create_by(name: 'San Bernardo',         code: '13401', state: rm)
Spree::County.find_or_create_by(name: 'Alhué',                code: '13502', state: rm)
Spree::County.find_or_create_by(name: 'Curacaví',             code: '13503', state: rm)
Spree::County.find_or_create_by(name: 'María Pinto',          code: '13504', state: rm)
Spree::County.find_or_create_by(name: 'Melipilla',            code: '13501', state: rm)
Spree::County.find_or_create_by(name: 'San Pedro',            code: '13505', state: rm)
Spree::County.find_or_create_by(name: 'Cerrillos',            code: '13102', state: rm)
Spree::County.find_or_create_by(name: 'Cerro Navia',          code: '13103', state: rm)
Spree::County.find_or_create_by(name: 'Conchalí',             code: '13104', state: rm)
Spree::County.find_or_create_by(name: 'El Bosque',            code: '13105', state: rm)
Spree::County.find_or_create_by(name: 'Estación Central',     code: '13106', state: rm)
Spree::County.find_or_create_by(name: 'Huechuraba',           code: '13107', state: rm)
Spree::County.find_or_create_by(name: 'Independencia',        code: '13108', state: rm)
Spree::County.find_or_create_by(name: 'La Cisterna',          code: '13109', state: rm)
Spree::County.find_or_create_by(name: 'La Granja',            code: '13111', state: rm)
Spree::County.find_or_create_by(name: 'La Florida',           code: '13110', state: rm)
Spree::County.find_or_create_by(name: 'La Pintana',           code: '13112', state: rm)
Spree::County.find_or_create_by(name: 'La Reina',             code: '13113', state: rm)
Spree::County.find_or_create_by(name: 'Las Condes',           code: '13114', state: rm)
Spree::County.find_or_create_by(name: 'Lo Barnechea',         code: '13115', state: rm)
Spree::County.find_or_create_by(name: 'Lo Espejo',            code: '13116', state: rm)
Spree::County.find_or_create_by(name: 'Lo Prado',             code: '13117', state: rm)
Spree::County.find_or_create_by(name: 'Macul',                code: '13118', state: rm)
Spree::County.find_or_create_by(name: 'Maipú',                code: '13119', state: rm)
Spree::County.find_or_create_by(name: 'Ñuñoa',                code: '13120', state: rm)
Spree::County.find_or_create_by(name: 'Pedro Aguirre Cerda',  code: '13121', state: rm)
Spree::County.find_or_create_by(name: 'Peñalolén',            code: '13122', state: rm)
Spree::County.find_or_create_by(name: 'Providencia',          code: '13123', state: rm)
Spree::County.find_or_create_by(name: 'Pudahuel',             code: '13124', state: rm)
Spree::County.find_or_create_by(name: 'Quilicura',            code: '13125', state: rm)
Spree::County.find_or_create_by(name: 'Quinta Normal',        code: '13126', state: rm)
Spree::County.find_or_create_by(name: 'Recoleta',             code: '13127', state: rm)
Spree::County.find_or_create_by(name: 'Renca',                code: '13128', state: rm)
Spree::County.find_or_create_by(name: 'San Miguel',           code: '13130', state: rm)
Spree::County.find_or_create_by(name: 'San Joaquín',          code: '13129', state: rm)
Spree::County.find_or_create_by(name: 'San Ramón',            code: '13131', state: rm)
Spree::County.find_or_create_by(name: 'Santiago',             code: '13101', state: rm)
Spree::County.find_or_create_by(name: 'Vitacura',             code: '13132', state: rm)
Spree::County.find_or_create_by(name: 'El Monte',             code: '13602', state: rm)
Spree::County.find_or_create_by(name: 'Isla de Maipo',        code: '13603', state: rm)
Spree::County.find_or_create_by(name: 'Padre Hurtado',        code: '13604', state: rm)
Spree::County.find_or_create_by(name: 'Peñaflor',             code: '13605', state: rm)
Spree::County.find_or_create_by(name: 'Talagante',            code: '13601', state: rm)
