---
ignore:
  # (2024/02/12) Ignore jQuery CVEs
  # jquery-ui-rails version 7.0 still hasnt been released on rubygems
  # and the current release of spree_backend doesnt support
  # tagged version 7.0
  - CVE-2021-41182
  - CVE-2021-41183
  - CVE-2021-41184
  - CVE-2022-31160
  # (2024/02/27) Ignore rack-cors CVEs
  # No patch for rack-cors has been available yet.
  - CVE-2024-27456
