version: '3.7'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "cenabast"
      POSTGRES_PASSWORD: "yourpassword"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - 'cenabast-postgres:/var/lib/postgresql/data'

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'

  web:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'opensearch'
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bash -c "rm -rf tmp/pids/server.pid && yarn install && yarn build && bundle exec rails s -b 0.0.0.0 -p 4000"
    ports:
      - '${DOCKER_HOST_WEB_PORT:-4000}:4000'
    volumes:
      - 'bundle_cache:/bundle'
      - '.:/app'
      - .env:/app/.env
    stdin_open: true
    tty: true
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: postgres
      DB_PORT: 5432
      DISABLE_SPRING: 1

  worker:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'opensearch'
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - 'bundle_cache:/bundle'
      - '.:/app'
      - .env:/app/.env
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: postgres
      DB_PORT: 5432
      DISABLE_SPRING: 1

  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    environment:
      discovery.type: single-node
      node.name: opensearch
      # Disables Security plugin
      DISABLE_SECURITY_PLUGIN: 'true'
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      # Disables security dashboards plugin in OpenSearch Dashboards
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
    depends_on:
      - opensearch

volumes:
  cenabast-postgres:
    external: true
  opensearch-data:
  redis:
  bundle_cache:
