version: "2.2"

services:
  elasticsearch:
    image: elasticsearch:8.12.2
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    volumes:
      - 'elasticsearch-data:/usr/share/elasticsearch/data'
  kibana:
    depends_on:
      - 'elasticsearch'
    image: docker.elastic.co/kibana/kibana:8.12.2
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      DISABLE_SECURITY_PLUGIN: true
      SERVERNAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  certs:
    driver: local
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local