name: Rspec

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      opensearch:
        image: opensearchproject/opensearch:2
        env:
          discovery.type: single-node
          node.name: opensearch
          # Disables Security plugin
          DISABLE_SECURITY_PLUGIN: 'true'
          OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
        ports:
          - 9200:9200
          - 9600:9600
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: cenabast
          POSTGRES_PASSWORD: yourpassword
          POSTGRES_DB: cenabast_test
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Ruby 3.2.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true
    - name: 'Setup DB, Run tests'
      run: |
        printenv
        bin/rails db:create db:schema:load
        bundle exec rspec
      env:
        RAILS_ENV: test
        DB_HOST: localhost
        DB_PORT: ${{ job.services.postgres.ports[5432] }}
        OPENSEARCH_URL: http://localhost:${{ job.services.opensearch.ports[9200] }}
